version: '3'

services:
  backend:
    build:
      context: ../OneDrive/Bureau/Assignement
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: ./
    ports:
      - "5000:5000"
    networks:
      - ecommerce-network
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8080

networks:
  ecommerce-network:
    driver: bridge
